apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: superset
  namespace: default
spec:
  interval: 5m
  url: https://apache.github.io/superset
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: superset
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: superset
      sourceRef:
        kind: HelmRepository
        name: superset
      interval: 1m
  values:
    extraEnvRaw:
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            name: superset-secrets
            key: postgres-password
    postgresql:
      auth:
        existingSecret: superset-secrets
    bootstrapScript: |
      #!/bin/bash
      if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
